@startuml
abstract class Pizzeria [[java:Pizzeria]] {
	+Pizzeria(PizzaFactory factory)
	+Pizza commanderPizza(String type)
	#Pizza creerPizza(String type)
}
class PizzaFactory [[java:PizzaFactory]] {
}
Pizzeria --> "1" PizzaFactory : factory
class PizzeriaBrest [[java:PizzeriaBrest]] {
	+PizzeriaBrest()
}
class Pizzeria [[java:Pizzeria]] {
}
Pizzeria <|-- PizzeriaBrest
abstract class Pizza [[java:Pizza]] {
	~String nom
	~String pate
	~String sauce
	~ArrayList<String> garnitures
	+void preparer()
	+void cuire()
	+void couper()
	+void emballer()
	+String getNom()
}
class PizzaPoivronsStyleBrest [[java:PizzaPoivronsStyleBrest]] {
}
class Pizza [[java:Pizza]] {
}
Pizza <|-- PizzaPoivronsStyleBrest
class PizzaGrecqueStyleStrasbourg [[java:PizzaGrecqueStyleStrasbourg]] {
}
class Pizza [[java:Pizza]] {
}
Pizza <|-- PizzaGrecqueStyleStrasbourg
class PizzaGrecqueStyleBrest [[java:PizzaGrecqueStyleBrest]] {
}
class Pizza [[java:Pizza]] {
}
Pizza <|-- PizzaGrecqueStyleBrest
class PizzaFromageStyleBrest [[java:PizzaFromageStyleBrest]] {
}
class Pizza [[java:Pizza]] {
}
Pizza <|-- PizzaFromageStyleBrest
class PizzaFromageStyleStrasbourg [[java:PizzaFromageStyleStrasbourg]] {
}
class Pizza [[java:Pizza]] {
}
Pizza <|-- PizzaFromageStyleStrasbourg
class PizzeriaStrasbourg [[java:PizzeriaStrasbourg]] {
	+PizzeriaStrasbourg()
}
class Pizzeria [[java:Pizzeria]] {
}
Pizzeria <|-- PizzeriaStrasbourg
class PizzaPoivronsStyleStrasbourg [[java:PizzaPoivronsStyleStrasbourg]] {
}
class Pizza [[java:Pizza]] {
}
Pizza <|-- PizzaPoivronsStyleStrasbourg
abstract class PizzaFactory [[java:PizzaFactory]] {
	#{abstract}Pizza creerPizza(String type)
}
class PizzaFactoryBrest [[java:PizzaFactoryBrest]] {
	-{static}PizzaFactory instance
	-PizzaFactoryBrest()
	+{static}PizzaFactory getInstance()
	#Pizza creerPizza(String type)
}
class PizzaFactory [[java:PizzaFactory]] {
}
PizzaFactory <|-- PizzaFactoryBrest
class PizzaFactoryStrasbourg [[java:PizzaFactoryStrasbourg]] {
	-{static}PizzaFactory instance
	-PizzaFactoryStrasbourg()
	+{static}PizzaFactory getInstance()
	#Pizza creerPizza(String type)
}
class PizzaFactory [[java:PizzaFactory]] {
}
PizzaFactory <|-- PizzaFactoryStrasbourg
@enduml